# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d2856c153a48cf5f1dd9201ab3309b564d4282c55868ed12eb1e7e32a662761143d025dd1d3518423c4141b9cd7515fc5d3649422b164baa5614ba0e7e89d1

test:
  secret_key_base: 9915778f41c931d686e22bccd5ccc9f1341e95cdb5e10bd3b175259c6818f068d5dede2614c3d240736dc68d94799c6c40d5df4be02d422b7a86ec0f042a2c33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
